name: Feature request
description: Propose a Community improvement
body:
  - type: textarea
    id: problem
    attributes: {label: Problem, description: Describe the user need without confidential information.}
    validations: {required: true}
  - type: textarea
    id: proposal
    attributes: {label: Proposed solution}
    validations: {required: true}
